In [2]:
import numpy as np
results = []
r = 0.0125

l1_values = np.array([0.5, 1.0, 2.0])  # Make dynamic

l2 = lambda r, l1 : np.sqrt(np.square(r / 2) + np.square(l1_values))
l3 = lambda r, l3 : np.sqrt(np.square(r) + np.square(l1_values))

l2_values = l2(r, l1_values)
l3_values = l3(r, l2_values)

print(l2_values)
print(l3_values)
print(l2_values - l1_values)
print(l3_values - l2_values)



[0.50003906 1.00001953 2.00000977]
[0.50015623 1.00007812 2.00003906]
[3.90609742e-05 1.95310593e-05 9.76560116e-06]
[1.17164619e-04 5.85908892e-05 2.92965174e-05]
